Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*.rb'
    - 'config/unicorn/*.rb'
    - 'spec/javascripts/support/jasmine_helper.rb'
    - 'config/initializers/rubycas-client.rb'

Style/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
