source 'https://rubygems.org'

gem 'rails', '4.2.7'
gem 'sass-rails'
gem 'pg'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'simplecov'
gem 'aasm'
gem 'i18n'
gem 'puma'
gem 'rubycas-client'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'rubocop'
  gem 'timecop'
  gem 'byebug'
  gem 'spring'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'shoulda-matchers'
  gem 'database_cleaner'
end
